spring.application.name=ecommerce 

image.path=images/
server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://db.ooaaaporhzvsucfpaupy.supabase.co:5432/postgres?sslmode=require

spring.datasource.username=postgres
spring.datasource.password=1@Midadhala
spring.jpa.hibernate.ddl-auto=update

# To check sql commecnts
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
image.base.url=https://sfskhqytrynivsacvzsx.supabase.co/storage/v1/object/public/images

# insert into category (category_name) values ('Pen'); 
# insert into category (category_name) values ('Pencil'); 
# insert into category (category_name) values ('A5 sheets'); 
# insert into category (category_name) values ('Long book'); 
# insert into category (category_name) values ('Short Book'); 
# insert into category (category_name) values ('Scale'); 
# insert into category (category_name) values ('School Unifrom'); 
# insert into category (category_name) values ('School Bus'); 
# insert into category (category_name) values ('Water Bottle'); 
# insert into category (category_name) values ('Fan'); 
# insert into category (category_name) values ('AC'); 
# insert into category (category_name) values ('Cooler'); 
# insert into category (category_name) values ('Munch'); 
# insert into category (category_name) values ('Remote bike'); 
# insert into category (category_name) values ('Remote car');
#  insert into category (category_name) values ('Remote heli pad'); 
#  insert into category (category_name) values ('School Bag'); 
#  insert into category (category_name) values ('Office laptop');
#   insert into category (category_name) values ('Asus laptop'); 
#   insert into category (category_name) values ('Acer latop');
#    insert into category (category_name) values ('MAc book'); 
#    insert into category (category_name) values ('Lenova'); 
#    insert into category (category_name) values ('Iphone'); 
#    insert into category (category_name) values ('one +'); 
#    insert into category (category_name) values ('Micromax');
#     insert into category (category_name) values ('Moto'); 
#     insert into category (category_name) values ('IQOO'); 
#     insert into category (category_name) values ('realme'); 
#     insert into category (category_name) values ('Redmi');
#      insert into category (category_name) values ('Oppo'); 
#      insert into category (category_name) values ('Vivo'); 
#      insert into category (category_name) values ('Infinix');
#       insert into category (category_name) values ('Honor');
#        insert into category (category_name) values ('BGMi');
#         insert into category (category_name) values ('Free Fire');
#          insert into category (category_name) values ('Mobile Case');
#           insert into category (category_name) values ('Charger');


spring.app.jwtSecret=mySecretKey1234567898aopsgjsfghsfhsfsdfgsfshsfh
spring.app.jwtExpirationMs=300000000
spring.ecom.app.jwtCookieName=springBootEcom